### ISSUE TITLE
Do not add empty list of sounds anymore

### ISSUE THREAD

**Issue by benjaminkomen** [benjaminkomen/TibiaWikiBot#120]
> [at]Bennie, I noticed your bot was adding `| sounds         = {{Sound List|}}` to all item pages it edited, can you change it so it won't add this parameter anymore (and won't remove it from items that emit sounds when used)?

**Comment by bennie** [comment]
I think you might be tagging the wrong person in this.

**Comment by benjaminkomen** [comment]
Sorry, I copied this from the report on Discord, didn't mean to tag @bennie on github..

**Comment by benjaminkomen** [comment]
Will be fixed in https://github.com/benjaminkomen/TibiaWikiBot/pull/151
