### ISSUE TITLE
Better regex to get creature names out of Template:Loot Item

### ISSUE THREAD

**Issue by benjaminkomen** [benjaminkomen/TibiaWikiBot#3]
The current regex in the method makeListOfLootItems() can't deal with a third optional parameter in Template:Loot Item containing rarity info. An ugly work-around is currently used to deal with this.

@Sixish, if you have any ideas, please let me know.

**Comment by Sixish** [comment]
I haven't ever used regular expressions with Java, but this will match all combinations:

    {{Loot Item\|([^\|]+)(\|([^\|]+))?(\|([^\|]+))?}}

Tested on:

    |{{Loot Item|Apple}}
    |{{Loot Item|0-4|Gold Coin}}
    |{{Loot Item|0-4|Gold Coin|very rare}}

**Comment by benjaminkomen** [comment]
![image](https://cloud.githubusercontent.com/assets/12815582/23368908/b78c71e6-fd0f-11e6-8f49-33cdf6c318a8.png)

Looks good, but ideally all matches are in the same group. According to regex101.com Apple is matched in group 1, but Gold Coin in case 2 and 3 are matched in group 3.

**Comment by Sixish** [comment]
Regular expressions are concerned with matching, not with how groupings make sense. The Java code should be responsible for making sense of the data matched. Extract the relevant data from the results using if-else branches. If you can see how many groupings there are in total, you know which case you are dealing with.

**Comment by benjaminkomen** [comment]
Ok, didn't knew that. Your regex is already quite an improvement, so I'll apply it. Thanks for your help!

**Comment by Sixish** [comment]
I would suggest making the character set more specific as well.

    {{Loot Item\|([^\|]+)(\|([^\|]+))?(\|([^\|]+))?}}

This regex will technically match this:

    {{Loot Item|Apple}}{{Loot Item|Orange}}

...as one match, not two as you would expect; that's because the character set [^\|] includes the } character, which means you allow premature ending of the template.

If we use this:

    {{Loot Item\|(([^|}]+)(\|([^|}]+))?(\|([^|}]+))?)}}

...the regex will see the } and stop there.
