### ISSUE TITLE
DEBUG=false means DEBUG=true?

### ISSUE THREAD

**Issue by Sixish** [benjaminkomen/TibiaWikiBot#8]
https://github.com/benjaminkomen/TibiaWikiBot/blob/27ff9dfc979c3aaa2610a00079c61a1a8a94398d/src/main/java/com/wikia/tibia/usecases/FixCreatures.java#L176-L180

Seems very strange that the bot operates (saves) when the debug mode is on, and writes to logs when it's off.

**Comment by benjaminkomen** [comment]
Correct. I already fixed this, but haven't commited it yet.
