### ISSUE TITLE
Fix class responsibilities

### ISSUE THREAD

**Issue by Sixish** [benjaminkomen/TibiaWikiBot#9]
TibiaWikiBot doesn't seem to be responsible for anything. It seems TibiaWikiBot should be responsible for wrapping MediaWikiBot and WikiRepository so that FixCreatures shouldn't have to interact with those classes.

FixCreatures and FixItems should be connected in some way. They are fundamentally tasks for TibiaWikiBot. It's more appropriate to have TibiaWikiBot acting upon the task, than the task creating its own bot. Alternatively, FixCreatures could extend TibiaWikiBot and be a bot in itself.

**Comment by Sixish** [comment]
While at it, it doesn't seem appropriate that the TibiaWikiBot is responsible for retrieving the account credentials. TibiaWikiBot should provide another login method which accepts an object of type AccountCredentials (custom); the main class should be responsible for reading this from the properties file.

**Comment by benjaminkomen** [comment]
Fixed in #11
